version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: "!ChangeMe!"
      POSTGRES_USER: app
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  node:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run dev-server"
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - php

  python_api:
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      - ./API:/app
      - ./var:/app/var
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${APP_ENV:-prod}
    depends_on:
      - database

volumes:
  database_data:
