version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      - database
    environment:
      APP_ENV: ${APP_ENV:-dev}  # Default to dev if not specified
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/app?serverVersion=16&charset=utf8"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  python_api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./API:/app:rw
    environment:
      FLASK_ENV: production
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/app"
    depends_on:
      - database

volumes:
  database_data:
