name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Deps
      run: sudo apt install docker docker-compose
    - uses: actions/checkout@v4
    - name: Run Docker Compose
      run: docker-compose up --build
